//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework17
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int id { get; set; }
        public string email { get; set; }
        public int code { get; set; }
        public string goodName { get; set; }
    }
}
